version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres_main:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_DB: main_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data

  postgres_service:
    image: postgres:15
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_DB: service_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_service_data:/var/lib/postgresql/data

  backend_main:
    build: ./main_backend
    container_name: backend_main
    depends_on:
      - postgres_main
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - ./main_backend:/app
    environment:
      - PYTHONPATH=/app
#  backend_service:
#    build: ./service_backend
#    container_name: backend_service
#    depends_on:
#      - postgres_service
#      - rabbitmq
#    ports:
#      - "4000:4000"

  celery_worker:
    build: ./main_backend
    command: celery -A celery_app.celery_app worker --loglevel=info
    depends_on:
      - backend_main
      - redis
    volumes:
      - ./main_backend:/app
    environment:
      - PYTHONPATH=/app

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    ports:
#      - "5173:5173"


volumes:
  postgres_main_data:
  postgres_service_data: