version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # port do komunikacji aplikacji
      - "15672:15672" # panel web (http://localhost:15672, login: guest/guest)

  postgres_main:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main_db
    ports:
      - "5433:5432"

  postgres_service:
    image: postgres:15
    container_name: postgres_service
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: service_db
    ports:
      - "5434:5432"

  backend_main:
    build: ./backend_main
    container_name: backend_main
    depends_on:
      - postgres_main
      - rabbitmq
    ports:
      - "8000:8000"

  backend_service:
    build: ./backend_service
    container_name: backend_service
    depends_on:
      - postgres_service
      - rabbitmq
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"